### ISSUE TITLE
テンプレートをPugからEJSに切り替える

### ISSUE THREAD

**Issue by lig-dsktschy** [liginc/laravel-mix-boilerplate-static#2]
## 理由
前提として、標準の言語（HTML/CSS/JS）のスーパーセットである言語を採用したい。

* Pug
HTMLのスーパーセットではない（ヒアドキュメントを使用しないとHTMLを記述できない）
if / for / include などの構文とHTMLは併用できない。

* EJS
HTMLのスーパーセットである（HTMLをそのまま記述できる）
if / for / include などの構文と併用できる。

## boilerplate-wordpressへの反映
**不要**
WordPressでEJSは使用されないため。

**Comment by mtmtkzm** [comment]
Pug 需要は 0 ...?
今、すでに Pug で動いてるプロジェクト的に大丈夫でしょうか？

**Comment by dsktschy** [comment]
> Pug 需要は 0 ...?
* 好みの話なら、0ではないかもしれないです
* 機能の話なら、Pugでしか出来ない機能がextendsくらいなので、ほぼ0かなと

> 今、すでに Pug で動いてるプロジェクト的に大丈夫でしょうか？
Boilerplateはcloneして使用するので、Boilerplate Repoの変更が、プロジェクトRepoに影響することは無いと考えてます。

加えて、Pugプラグインが以下の問題を持っているため、非推奨にしたいという理由もあります。
* 追加 / 削除を検知しない
* 開発者の反応が遅い(○ヶ月レベルで反応がない)

どうしても使用したければ、Gitの履歴としては残るので、設定を参照することが可能です。

**Comment by lig-dsktschy** [comment]
> Pug 需要は 0 ...?

* 好みの話なら、0ではないかもしれないです
* 機能の話なら、Pugでしか出来ない機能がextendsくらいなので、ほぼ0かなと

> 今、すでに Pug で動いてるプロジェクト的に大丈夫でしょうか？

Boilerplateはcloneして使用するので、Boilerplate Repoの変更がプロジェクトRepoに影響することは無いと考えてます。

加えて、Pugプラグインが以下の問題を持っているため、非推奨にしたいという理由もあります。

* 追加 / 削除を監視しない
* 開発者の反応が遅い(○ヶ月レベルで反応がない)

どうしても使用したければ、Gitの履歴としては残るので、設定を参照することが可能です。

**Comment by mtmtkzm** [comment]
https://github.com/liginc/laravel-mix-boilerplate-static/pull/3
